
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "left+-left*/rightUMINUSNUMBER VARstat : VAR '=' expstat : expexp : exp '+' expexp : exp '-' expexp : exp '*' expexp : exp '/' expexp : '-' exp %prec UMINUSexp : '(' exp ')'exp : NUMBERexp : VAR"
    
_lr_action_items = {'VAR':([0,4,5,7,8,9,10,11,],[2,13,13,13,13,13,13,13,]),'-':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[4,-10,9,4,4,-9,4,4,4,4,4,-7,-10,9,9,-3,-4,-5,-6,-8,]),'(':([0,4,5,7,8,9,10,11,],[5,5,5,5,5,5,5,5,]),'NUMBER':([0,4,5,7,8,9,10,11,],[6,6,6,6,6,6,6,6,]),'$end':([1,2,3,6,12,13,15,16,17,18,19,20,],[0,-10,-2,-9,-7,-10,-1,-3,-4,-5,-6,-8,]),'=':([2,],[7,]),'+':([2,3,6,12,13,14,15,16,17,18,19,20,],[-10,8,-9,-7,-10,8,8,-3,-4,-5,-6,-8,]),'*':([2,3,6,12,13,14,15,16,17,18,19,20,],[-10,10,-9,-7,-10,10,10,10,10,-5,-6,-8,]),'/':([2,3,6,12,13,14,15,16,17,18,19,20,],[-10,11,-9,-7,-10,11,11,11,11,-5,-6,-8,]),')':([6,12,13,14,16,17,18,19,20,],[-9,-7,-10,20,-3,-4,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stat':([0,],[1,]),'exp':([0,4,5,7,8,9,10,11,],[3,12,14,15,16,17,18,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stat","S'",1,None,None,None),
  ('stat -> VAR = exp','stat',3,'p_Expression_0','output.py',23),
  ('stat -> exp','stat',1,'p_Expression_1','output.py',27),
  ('exp -> exp + exp','exp',3,'p_Expression_2','output.py',31),
  ('exp -> exp - exp','exp',3,'p_Expression_3','output.py',35),
  ('exp -> exp * exp','exp',3,'p_Expression_4','output.py',39),
  ('exp -> exp / exp','exp',3,'p_Expression_5','output.py',43),
  ('exp -> - exp','exp',2,'p_Expression_6','output.py',47),
  ('exp -> ( exp )','exp',3,'p_Expression_7','output.py',51),
  ('exp -> NUMBER','exp',1,'p_Expression_8','output.py',55),
  ('exp -> VAR','exp',1,'p_Expression_9','output.py',59),
]
